version: '3.8'

services:
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    restart: always
  node:
    build:
      context: .
      dockerfile: dockerfiles/node.dockerfile
    env_file:
      - ./env/node.env
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mysql
    stdin_open: true
    tty: true
   